### PR TITLE
Http unit tests

### PR DESCRIPTION
**Pull request by bertfrees**
Depends on:
- [x] https://github.com/daisy/pipeline-framework/pull/94
- [x] https://github.com/daisy/pipeline-build-utils/pull/24

### CODE REVIEW

**Comment by josteinaj** [comment]
Hmm, this doesn't work out-of-the-box for me. It to use an old version of the framework which doesn't include daisy/pipeline-framework#94, but even if I change the version to 1.10.0-SNAPSHOT (and `mvn install` the patched version of the framework locally) it doesn't work.

Here's the error I get from this branch now:

```
ERROR: Bundle org.daisy.pipeline.framework-volatile [51] Error starting file:/tmp/1452867067091-0/bundles/org.daisy.pipeline.framework-volatile_2.0.1.SNAPSHOT.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.daisy.pipeline.framework-volatile [51]: Unable to resolve 51.0: missing requirement [51.0] osgi.wiring.package; (&(osgi.wiring.package=org.daisy.pipeline.clients)(version>=3.0.0)(!(version>=4.0.0))))
org.osgi.framework.BundleException: Unresolved constraint in bundle org.daisy.pipeline.framework-volatile [51]: Unable to resolve 51.0: missing requirement [51.0] osgi.wiring.package; (&(osgi.wiring.package=org.daisy.pipeline.clients)(version>=3.0.0)(!(version>=4.0.0)))
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
	at java.lang.Thread.run(Thread.java:745)
jan 15, 2016 3:11:08 PM org.ops4j.pax.exam.forked.ForkedTestContainer verifyThatBundlesAreResolved
SEVERE: Bundle [51] is not resolved
```

If I change framework-bom to 1.10.0-SNAPSHOT this is what I get:

```
ERROR: Bundle org.daisy.pipeline.calabash-adapter [43] Error starting file:/tmp/1452867632873-0/bundles/org.daisy.pipeline.calabash-adapter_2.0.3.SNAPSHOT.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.daisy.pipeline.calabash-adapter [43]: Unable to resolve 43.0: missing requirement [43.0] osgi.wiring.package; (&(osgi.wiring.package=org.daisy.pipeline.event)(version>=2.2.0)(!(version>=3.0.0))))
org.osgi.framework.BundleException: Unresolved constraint in bundle org.daisy.pipeline.calabash-adapter [43]: Unable to resolve 43.0: missing requirement [43.0] osgi.wiring.package; (&(osgi.wiring.package=org.daisy.pipeline.event)(version>=2.2.0)(!(version>=3.0.0)))
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
	at java.lang.Thread.run(Thread.java:745)
jan 15, 2016 3:20:34 PM org.ops4j.pax.exam.forked.ForkedTestContainer verifyThatBundlesAreResolved
SEVERE: Bundle [43] is not resolved
```

**Comment by bertfrees** [comment]
You can use framework-bom 1.10.0, it's released. But anyway, I get more or less the same error as you. It seems to resolve the dependency "framework-core:2.3.0-SNAPSHOT" for some reason (you can see that in the logs) while it should be "3.0.0".

**Comment by bertfrees** [comment]
Oh yes, I remember, the version was defined in the Java file. Let me push an update, now it works.

**Comment by bertfrees** [comment]
Never mind my previous comments about the version of framework-core. That was something in a local commit. But anyway, I got it working. I've also pushed the local commit which is unfinished, but maybe you can use it.

**Comment by josteinaj** [comment]
It works!

I thought this didn't work for a moment either but I realized that I can't run DP2 in the background while running the tests, since they bind to the same port :).

A couple of hours ago I released a version of clientlib-java that supports default values, and I have it working with the webui as well (daisy/pipeline-webui@e4a3447d210c1aca477e360fa261afb57b91264b). I can probably make use of your datatype/default value commit for tests though, so thanks!

**Comment by josteinaj** [comment]
Superseded by #18

**Pull request closed without merging**
