### PR TITLE
v4.7.0

### PR DESCRIPTION
**Pull request by josteinaj**
- Progress logic in dedicated class
- OSGi headers
- Message.getProgressInfo()
- Messages without progress info now nested under preceding progress message
- Support multiline messages
- Support globs in subnames for cases where the full name is not known

### CODE REVIEW

**Comment by josteinaj** [comment]
@bertfrees I changed it so that you still require a subname for progress messages to not be ignored, but you can now use globs to match subnames. I think that's what we agreed in chat. Note that I did it so that globs only match the first following occurence (since otherwise a `*` would match all following messages), so in the case of PxTransform, you could for instance use `[progress 1 *.PxTransformStep.run]`, but the first matching message in PxTransformStep.java would need to create another subname (for instance `[progress org.daisy…PxTransformStep.run 1 org.daisy…PxTransformStep.exec]` or whatnot, hope that makes sense).

If you're happy with how it is now I can make a release of this (and a release of the webui including this clientlib release after that).

**Comment by bertfrees** [comment]
Great. I remember we talked just about a special `*` identifier, not full support for globs, but it's a great extension to the idea :) Only matching the first following occurrence was indeed the idea yes. The main reason for me for using the `*` was actually to be able to skip any `px:transform` messages altogether (the main reason being that `px:transform`s can be nested). As far as I understand that is still possible with your changes. So I'm happy.

Just one question: what happens if no messages match the pattern?

**Comment by josteinaj** [comment]
> Just one question: what happens if no messages match the pattern?

The same thing as if no messages match a normal non-glob message; it will ignore messages with a name not in the "current progress path":

```
[progress name 100 subname]
[progress other 100] <-- ignored
[progress subname 100]

[progress name 100 sub*]
[progress other 100] <-- ignored
[progress subname 100]

[progress name 100 sub*]
[progress other 100] <-- ignored
[progress subtype 100]
[progress subname 100] <-- ignored

[progress name 100 sub*]
[progress other 100] <-- ignored
[progress name 100] <-- discards previously declared subname
[progress subname 100] <-- ignored
```

**Comment by bertfrees** [comment]
OK perfect.

**Pull request merged**
