### PR TITLE
Unit tests and some fixes for remote mode

### PR DESCRIPTION
**Pull request by bertfrees**

### CODE REVIEW

**Comment by bertfrees** [comment]
Thanks. OK I'll look into it again.

**Comment by bertfrees** [comment]
This PR replaces https://github.com/daisy/pipeline-clientlib-java/pull/10.

**Comment by bertfrees** [comment]
@rdeltour I tried this again, this time from within the sub-repo, and I'm not getting the error you are getting. Your stack trace points to a line in JobValidator that does not match with anything in the source code so that must mean that the wrong clientlib-java test dependency is getting pulled in for you. Is it possible that you haven't built the clientlib-java module before building clientlib-java-httpclient?

**Comment by rdeltour** [comment]
> Is it possible that you haven't built the clientlib-java module before building clientlib-java-httpclient?

I don't think so. I'm on the `remote` branch, uncommented the `clientlib-java-httpclient` module from the aggregator POM, and ran `mvn clean test` on the aggregator.

**Comment by bertfrees** [comment]
Try `mvn clean install`. The Pax-Exam tests require that the dependencies are installed in the local maven repo.

**Comment by rdeltour** [comment]
> The Pax-Exam tests require that the dependencies are installed in the local maven repo.

Oh right 🤦‍♂️. `mvn clean install` did the trick.

The Javadoc plugin failed however, probably due to the bigger restrictions in Java 8. I think it needs to be configured explicitly with Java 7-level compliance.

Btw, the `clientlib-java-httpclient` module is commented in the aggregator (in this branch), so the CI build is not very helpful :-)

**Comment by bertfrees** [comment]
> The Javadoc plugin failed however, probably due to the bigger restrictions in Java 8. I think it needs to be configured explicitly with Java 7-level compliance.

I've tried that but couldn't get it to work. As long as I build with JDK 8 it does not work.

**Comment by bertfrees** [comment]
@josteinaj Does the Javadoc phase not fail for you?

**Comment by rdeltour** [comment]
>>    The Javadoc plugin failed however, probably due to the bigger restrictions in Java 8. I think it needs to be configured explicitly with Java 7-level compliance.
>
> I've tried that but couldn't get it to work. As long as I build with JDK 8 it does not work.

IIRC `-Xdoclint:none` should do the trick, it's [enabled in the parent POM](https://github.com/daisy/maven-parents/blob/master/daisy-parent/pom.xml#L357) from version 4.

I would push updated POMs, but the branch was deleted.

**Comment by bertfrees** [comment]
Yeah, merged already. I have restored the branch now so you can push.

**Comment by rdeltour** [comment]
> I have restored the branch now so you can push.

well, I had updates the DAISY parent POMs to version 4, but now I get a rather obscure error

```
[SUREFIRE] std/in stream corrupted
java.io.IOException: Command NOOP unexpectedly read Void data with length 4.
	at org.apache.maven.surefire.booter.MasterProcessCommand.decode(MasterProcessCommand.java:139)
	at org.apache.maven.surefire.booter.CommandReader$CommandRunnable.run(CommandReader.java:360)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by bertfrees** [comment]
You didn't get that error before? Looks like this is the same error I got with several tests in pipeline-scripts and pipeline-modules-common.

Updating to pax-exam-helper 2.2.0 should in theory fix this but I can't get it to work yet. Working on it...

**Comment by bertfrees** [comment]
Does it work with my latest commit (2c0972a)?

**Comment by rdeltour** [comment]
> Does it work with my latest commit (2c0972a)?

Still failing, this time with another error... 😕

**Comment by bertfrees** [comment]
What is the problem?

**Comment by josteinaj** [comment]
@bertfrees Yes, the javadoc builds fine for me on both `master` and `remote` (just some warnings).

The httpclient does not pass its tests on `remote` though:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.daisy.pipeline.client.http.WSRemoteTest
2017-08-31 13:07:07.892:INFO:oejs.Server:jetty-7.6.5.v20120716
2017-08-31 13:07:07.909:INFO:oejs.AbstractConnector:Started SelectChannelConnector@localhost:8181
2017-08-31	13:07:08	127.0.0.1	-	127.0.0.1	8181	GET	/ws/alive	-	200	-	0	139	http://localhost:8181	Apache-HttpClient/4.2.5 (java 1.5)	-
2017-08-31	13:07:08	127.0.0.1	-	127.0.0.1	8181	GET	/ws/alive	-	200	-	0	3	http://localhost:8181	Apache-HttpClient/4.2.5 (java 1.5)	-
2017-08-31	13:07:08	127.0.0.1	-	127.0.0.1	8181	GET	/ws/scripts/foo:script	authid=clientid&time=2017-08-31T11:07:08Z&nonce=452824207196934061792297484692&sign=H1ccoS1%2B5wknEBISihDC0xF6h6o=	200	-	0	39	http://localhost:8181	Apache-HttpClient/4.2.5 (java 1.5)	-
CHANGING STATUS IN THE DB BEFORE POSTING IT!
CHANGING STATUS IN THE DB BEFORE POSTING IT!
2017-08-31	13:07:08	127.0.0.1	-	127.0.0.1	8181	POST	/ws/jobs	authid=clientid&time=2017-08-31T11:07:08Z&nonce=533928242108653375534214215137&sign=UZTK7Z8SfAxhaeC764dHbPo6xx0=	201	-	1107	94	http://localhost:8181	Apache-HttpClient/4.2.5 (java 1.5)	-
CHANGING STATUS IN THE DB BEFORE POSTING IT!
2017-08-31	13:07:10	127.0.0.1	-	127.0.0.1	8181	GET	/ws/jobs/7e735ff0-6f9b-4a0b-b0a6-b279ed1bd0ef	authid=clientid&time=2017-08-31T11:07:10Z&nonce=655297948808102307264857903035&sign=v/KXvQVs0iIB6g1YUFlCkDLaLXE=	200	-	0	10	http://localhost:8181	Apache-HttpClient/4.2.5 (java 1.5)	-
2017-08-31	13:07:10	127.0.0.1	-	127.0.0.1	8181	GET	/ws/jobs/7e735ff0-6f9b-4a0b-b0a6-b279ed1bd0ef/result/option/output-dir/idx/output-dir/result.xml	-	200	2550	11	http://localhost:8181	Java/1.8.0_131	-
ERROR: org.daisy.pipeline.calabash-adapter (53): [calabash-xproc-engine] The unsetPropertyPublisherFactory method has thrown an exception
java.lang.NullPointerException
	at org.daisy.common.properties.Property.equals(Property.java:19)
	at java.util.LinkedList.remove(LinkedList.java:365)
	at org.daisy.common.properties.PropertyTracker.deleteProperty(PropertyTracker.java:78)
	at org.daisy.common.properties.PropertyPublisher.unpublish(PropertyPublisher.java:70)
	at org.daisy.common.properties.PropertyPublisher.unpublish(PropertyPublisher.java:65)
	at org.daisy.common.xproc.calabash.impl.CalabashXProcEngine.unsetPropertyPublisherFactory(CalabashXProcEngine.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.felix.scr.impl.helper.BaseMethod.invokeMethod(BaseMethod.java:236)
(...)
```

My setup, in case it matters:
```
➜  clientlib-java-httpclient git:(remote) ✗ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

➜  clientlib-java-httpclient git:(remote) ✗ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.17.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

➜  clientlib-java-httpclient git:(remote) ✗ echo $JAVA_HOME 
/usr/lib/jvm/java-8-openjdk-amd64

➜  clientlib-java-httpclient git:(remote) ✗ mvn --version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: nb_NO, platform encoding: UTF-8
OS name: "linux", version: "4.13.0-041300rc7-generic", arch: "amd64", family: "unix"
```

**Comment by bertfrees** [comment]
Why is the test failing? It passes on my machine so I need some more info.

**Comment by bertfrees** [comment]
The Javadoc doesn't build for Romain and I. Unless anyone knows another way to make it work I suggest we just fix the warnings?

**Comment by josteinaj** [comment]
Btw, I forgot to say, by default on the `remote` branch I'm getting an error from maven that stops the build before it gets to the javadoc building:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.0.2:jar (default-jar) on project clientlib-java-httpclient: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. -> [Help 1]
```

If I change line 66 in clientlib-java-httpclient/pom.xml from:
```
                        <id>jar-before-test</id>
```
to:
```
                        <id>default-jar</id>
```
... it gets past that error and builds the javadoc correctly. Apparently that's a hack though, so I don't know if that's a good enough solution: https://stackoverflow.com/a/41214856/281065

**Comment by bertfrees** [comment]
Maybe that only happens with a more recent version of Maven than I have. Your solution sounds fine to me.

**Comment by josteinaj** [comment]
Attached is the full output from the `remote` branch with the failing tests.
[log.txt](https://github.com/daisy/pipeline-clientlib-java/files/1266833/log.txt)

**Comment by bertfrees** [comment]
Thanks. Hmm I thought this "unsetPropertyPublisherFactory" error only happened when run via xproc-engine-daisy-pipeline, and in that case it is harmless. But of course we're not running any XProcSpec tests here, and it seems it is indeed fatal in this case. Strange because it doesn't happen on my machine.

I have a Github issue for this: https://github.com/daisy/xproc-maven-plugin/issues/23. I also have done a fix for it in the mean time but I don't think I pushed it yet.

I'll push it and then maybe you can try with that new version of pipeline-framework.

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-framework/commit/a24536ee2cdb334938a4390d57b05446381d2b7b.

**Comment by josteinaj** [comment]
I've fixed the warnings on the `remote` branch now.

And actually, it seems that what I thought was an error earlier is just an exception that is ignored. So now the build succeeds for me.

```
➜  pipeline-clientlib-java git:(remote) mvn clean install           
(...)
[INFO] Building DAISY Pipeline 2 :: Java Client Library 4.7.1-SNAPSHOT
(...)
[INFO] --- maven-javadoc-plugin:2.10.4:jar (attach-javadocs) @ clientlib-java ---
[INFO] 
Loading source files for package org.daisy.pipeline.client...
Loading source files for package org.daisy.pipeline.client.models...
Loading source files for package org.daisy.pipeline.client.models.datatypes...
Loading source files for package org.daisy.pipeline.client.utils...
Loading source files for package org.daisy.pipeline.client.filestorage...
Constructing Javadoc information...
Standard Doclet version 1.8.0_131
Building tree for all the packages and classes...
(...)
[INFO] Building jar: /home/jostein/daisy-pipeline/pipeline-clientlib-java/clientlib-java/target/clientlib-java-4.7.1-SNAPSHOT-javadoc.jar
(...)
[INFO] Building DAISY Pipeline 2 :: Java Client Library :: HTTP Client Implementation 2.0.1-SNAPSHOT
(...)
[INFO] --- maven-javadoc-plugin:2.10.4:jar (attach-javadocs) @ clientlib-java-httpclient ---
[INFO] 
Loading source files for package org.daisy.pipeline.client.http...
Constructing Javadoc information...
Standard Doclet version 1.8.0_131
Building tree for all the packages and classes...
(...)
[INFO] Building jar: /home/jostein/daisy-pipeline/pipeline-clientlib-java/clientlib-java-httpclient/target/clientlib-java-httpclient-2.0.1-SNAPSHOT-javadoc.jar
(...)
[INFO] DAISY Pipeline 2 :: Java Client Library ............ SUCCESS [  5.350 s]
[INFO] DAISY Pipeline 2 :: Java Client Library :: HTTP Client Implementation SUCCESS [ 11.222 s]
[INFO] DAISY Pipeline 2 :: Aggregator POM for the Java Client Library SUCCESS [  0.021 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.184 s
[INFO] Finished at: 2017-08-31T13:41:03+02:00
[INFO] Final Memory: 50M/591M
[INFO] ------------------------------------------------------------------------
```

**Comment by bertfrees** [comment]
Great! So it was not fatal after all, makes sense.

**Comment by bertfrees** [comment]
As agreed on Slack, I'll leave merging the remaining commits (and possibly rewriting the master branch) up to you.

**Comment by josteinaj** [comment]
Ok, I think the branches are good now. Build still succeeds for me.

**Comment by rdeltour** [comment]
I've just pulled the latest branch, and the build fails for me (same error as in Travis) 😕

**Comment by bertfrees** [comment]
Fails for me too now...

**Comment by josteinaj** [comment]
Could you add this as line 43 in WSRemoteTest.java, and let me know what the output is?

```java
System.out.println("BASEDIR="+BASEDIR);
```

**Comment by bertfrees** [comment]
Fixed it.

**Comment by bertfrees** [comment]
Wait it wasn't pushed, hold on.

**Comment by josteinaj** [comment]
Still succeeds here.

**Comment by josteinaj** [comment]
Let me know if this branch is complete, and I'll make a release of it.

**Comment by bertfrees** [comment]
Ready as far as I'm concerned!

**Pull request merged**
